### ISSUE TITLE
manjaro-sway PGP key outdated

### ISSUE THREAD

**Issue by ReeSilva** [Manjaro-Sway/manjaro-sway#69]
The PGP signature for the `manjaro-sway` database is outdated since this morning, avoiding the update of packages or installation of any new one.

Steps to reproduce:
Run `yay -Syuu` or `sudo pacman -Syuu`

Confirm that you want to import the key. It will returns to you that you can't because it can't reach it.

```
~
13:36:30 ✗ yay -Syuu                                                                                                                                                                                    13:36:30
erro: manjaro-sway: a chave "A44C644D792767CED7941AFEABB2075D5F310CF8" é desconhecida
:: Importar a chave PGP A44C644D792767CED7941AFEABB2075D5F310CF8? [S/n] S
erro: a chave "A44C644D792767CED7941AFEABB2075D5F310CF8" não pôde ser procurada remotamente
:: Sincronizando a base de dados de pacotes...
 core está atualizado
 extra está atualizado
 community está atualizado
 multilib está atualizado
 manjaro-sway                                                                                      9,5 KiB  0,00   B/s 00:00 [############################################################################] 100%
 manjaro-sway.sig                                                                                438,0   B  0,00   B/s 00:00 [############################################################################] 100%
erro: manjaro-sway: a chave "A44C644D792767CED7941AFEABB2075D5F310CF8" é desconhecida
:: Importar a chave PGP A44C644D792767CED7941AFEABB2075D5F310CF8? [S/n] S
erro: a chave "A44C644D792767CED7941AFEABB2075D5F310CF8" não pôde ser procurada remotamente
erro: falha ao atualizar manjaro-sway (base de dados inválida ou corrompida (assinatura PGP))
erro: falha ao sincronizar todos as bases de dados
erro ao instalar pacotes do repositório
```

**Comment by Birate** [comment]
I ran into this issues 30min ago.

`sudo pacman-key --recv-keys A44C644D792767CED7941AFEABB2075D5F310CF8 --keyserver keyserver.ubuntu.com`

and you should be good to go

**Comment by ReeSilva** [comment]
@Birate Thank you a lot :D It works

**Comment by Birate** [comment]
This might be problem for more people, could we keep this open until issues is solved.

**Comment by ReeSilva** [comment]
Done :D

**Comment by haukened** [comment]
Yeah thanks for keeping this open - this was the first place i came to look.
any reason this wouldn't have happened automatically?  i have my `$HOME/.gnupg/gpg.conf` set to `keyserver hkps://keyserver.ubuntu.com` so shouldn't `pacman-key` look there by default? or is that configured elsewhere?

**Comment by boredland** [comment]
Hi there! We're currently in the process of signing everything so we can submit it to the official Manjaro repos. 

Step one is signing all the packages and requesting our key to be added to the Manjaro keyring. This will take some time, but not too long. Hang in there ;-)

**Comment by Birate** [comment]
@haukened (To take with a grain of salt) `pacman-key` and your personal gpg keys are not stored at the same location. , pacman-key has a `--confdir` option to redirect to yout `.gnupg` dir

**Comment by boredland** [comment]
> @haukened (To take with a grain of salt) `pacman-key` and your personal gpg keys are not stored at the same location. , pacman-key has a `--confdir` option to redirect to your `.gnupg` dir
> 

Oh, thank you! I always added keys to both and feel very ill-informed now.

**Comment by boredland** [comment]
@Birate don't you mean the `--gpgdir` parameter?

**Comment by frytkisasmaczne** [comment]
Did something about the key change? I'm getting this from `sudo pacman -Syu --needed`

`error: manjaro-sway: signature from "Jonas Strassel <jonas.strassel@manjaro.org>" is invalid
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 manjaro-sway               130,0   B  0,00   B/s 00:00 [##############################] 100%
 manjaro-sway.sig           438,0   B  0,00   B/s 00:00 [##############################] 100%
error: manjaro-sway: signature from "Jonas Strassel <jonas.strassel@manjaro.org>" is invalid
error: failed to update manjaro-sway (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases`

**Comment by boredland** [comment]
> Did something about the key change?

ya, I broke our package-repo. m'onit

**Comment by boredland** [comment]
should be back to normal.

**Comment by Mathew-D** [comment]
I am still getting the error.
sudo pacman-key --keyserver keys.openpgp.org --recv-key A44C644D792767CED7941AFEABB2075D5F310CF8                                                                                                                   
gpg: key ABB2075D5F310CF8: "Jonas Strassel <jonas.strassel@manjaro.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
    ~  sudo pacman -Syu --needed                                                                                                                                                                                             ✔ 
error: manjaro-sway: signature from "Jonas Strassel <jonas.strassel@manjaro.org>" is invalid
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 manjaro-sway                                                                                                 130.0   B   659   B/s 00:00 [####################################################################################] 100%
 community is up to date
 multilib is up to date
error: manjaro-sway: signature from "Jonas Strassel <jonas.strassel@manjaro.org>" is invalid
error: failed to synchronize all databases (unexpected error)

**Comment by andrius** [comment]
I have fixed key issues but then there is another one, manjaro-sway.db is not in the right format. How to fix this one?

```shell
pacman -Syyu
# ...
error: could not open file /var/lib/pacman/sync/manjaro-sway.db: Unrecognized archive format
warning: manjaro-sway-settings: local (4.3.2-5) is newer than community (1.0.0-1)
error: failed to prepare transaction (invalid or corrupted database)

cat /var/lib/pacman/sync/manjaro-sway.db
version https://git-lfs.github.com/spec/v1
oid sha256:324
```

**Comment by FallenChromium** [comment]
I still have an issue with the signature, `manjaro-sway: signature from "Jonas Strassel <jonas.strassel@manjaro.org>" is invalid`. @andrius, can you please share how did you fix it?

**Comment by frytkisasmaczne** [comment]
@FallenChromium, i did `sudo rm /var/lib/pacman/sync/manjaro-sway.db.sig` and got the same stuff as andrius.
I don't think this is any better though.
If you also remove `/var/lib/pacman/sync/manjaro-sway.db`, then it will redownload both the db and db.sig and you'll be back where you are now.

**Comment by ohthehugemanatee** [comment]
Same problem here. 

I've tried:
- `sudo pacman-mirrors -f`
- `sudo pacman-key --init; sudo pacman-key --populate`
- `sudo pacman -Scc`
- `gpg --keyserver keyserver.ubuntu.com --recv-keys A44C644D792767CED7941AFEABB2075D5F310CF8` (also as root)
- `sudo pacman-key --keyserver keyserver.ubuntu.com --recv-keys A44C644D792767CED7941AFEABB2075D5F310CF8`

What's interesting is that according to `gpg --list-keys`, Jonas' key is just fine (expires 2023-07-07). 

```
pub   rsa3072 2021-07-07 [SC] [expires: 2023-07-07]
      A44C644D792767CED7941AFEABB2075D5F310CF8
uid           [ unknown] Jonas Strassel <jonas.strassel@manjaro.org>
sub   rsa3072 2021-07-07 [E] [expires: 2023-07-07]
```
When I try to manually validate the package db, gpg agrees that it's invalid (signed at 22:13 UTC):

```bash
~ 
❯ gpg --verify /var/lib/pacman/sync/manjaro-sway.db.sig /var/lib/pacman/sync/manjaro-sway.db                                                                                                                       
gpg: Signature made Mi 14 Jul 2021 00:13:59 CEST
gpg:                using RSA key A44C644D792767CED7941AFEABB2075D5F310CF8
gpg: BAD signature from "Jonas Strassel <jonas.strassel@manjaro.org>" [unknown]

```

**Comment by ohthehugemanatee** [comment]
also when I ignore package signatures, I get the same issue as @andrius . Invalid DB. On inspection, `manjaro-sway.db` is a text file and not the expected tgz contents. 

```zsh
~ 
❯ cat /var/lib/pacman/sync/manjaro-sway.db                                                                                                                                                                    [130]
version https://git-lfs.github.com/spec/v1
oid sha256:324f398c4fd437d86a1d8c427cfd33363fa6c21deba38deaf9aa9829d38ef3a9
size 14349

```

**Comment by boredland** [comment]
Hi! So the problem is, that I tried to switch to git-lfs in our packages repo. Sadly this invalidates all signatures, because I calculate them on a machine without git-lfs. I reverted all of that and hopefully it just works again now. I think it does. Sorry for the fuzz.

Regarding the primary issue of this ticket: I received word from @philmmanjaro some days ago, that it is on the way.

**Comment by FallenChromium** [comment]
Not exactly on the matter of this topic, but because the issue is resolved and I created myself a new one while trying to resolve this: I replaced the pacman.conf with pacman.conf.pacnew, thinking it might be the old pacman config causing the issue, and of course lost the manjaro-sway repo from it. How can I add it back?

**Comment by quiver4arrow** [comment]
I grabbed the manjaro sway ISO a couple of hours ago and I'm getting the same error, are you sure it's been fixed?

**Comment by fraunos** [comment]
Had the same issue just now with the latest iso.
manjaro-sway-21.0-210713-linux510

**Comment by boredland** [comment]
which issue? the missing key (https://github.com/Manjaro-Sway/manjaro-sway#unknown-public-key) or the broken signature? Broken signature should be fixed, for the key missing in the keyring package we're still waiting for it to be added (https://gitlab.manjaro.org/packages/core/manjaro-keyring)

**Comment by ohthehugemanatee** [comment]
I still get a key error every few days using `pamac`. It is resolved by running `pacman -Syyu` to refresh everything. PITA but it works...

**Comment by boredland** [comment]
ya, I think I whitnessed it too.wonder why that happens tho. its not like we change anything 🤷🏼

**Comment by FallenChromium** [comment]
Can confirm that it happens with pamac. As a wild guess, it could be a problem with cache invalidation, but a clean install is required to confirm 🤷🏻‍♂️

**Comment by chorriwuarri** [comment]
I just installed manjaro sway to test sway for the first time.
i got the gpg key error i had to comment out the sway servers in the pacman configuration to get it working

I also have other problems with sway, it is totally unconfigured, waybar is not showing up and when I try to launch it it does not work and the keyboard shortcuts do not work either.

**Comment by FallenChromium** [comment]
Well, because you commented out manjaro sway servers you couldn't get our configuration package, of course it won't be configured 🤣

**Comment by chorriwuarri** [comment]
the installation was done without commenting the pacman configuration, it didn't give any problems

the desktop appeared already without configuration, when I tried to update it gave me the gpg error

**Comment by boredland** [comment]
the gpg error should be gone soonish: https://gitlab.manjaro.org/packages/core/manjaro-keyring/-/merge_requests/2

**Comment by boredland** [comment]
> the installation was done without commenting the pacman configuration, it didn't give any problems

1. you likely installed the massively outdated configuration from the manjaro repos
2. you probably didn't copy over the local config to your user dir (this is neither a manjaro, nor a sway specific thing you have to do to configure lots of things in most desktop environments)

So: allow our key, install from our repo, copy over the skel.

**Comment by boredland** [comment]
the pgp key is now in manjaro keyring for arm and amd64
